// Generated by CoffeeScript 1.7.1
(function() {
  var Calendar, CalendarView, Plugin,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Plugin = app.get('plugin');

  Calendar = (function(_super) {
    __extends(Calendar, _super);

    function Calendar() {
      return Calendar.__super__.constructor.apply(this, arguments);
    }

    Calendar.prototype.defaults = {
      id: 'calendar',
      title: 'Calendar',
      navigatable: true,
      assets: {
        'stylesheet': 'calendar.css',
        'template': 'calendar.template.html',
        'js': {
          path: 'calendar-buffer.js',
          preload: true
        }
      }
    };

    return Calendar;

  })(Plugin.Blueprint.get('model'));

  CalendarView = (function(_super) {
    __extends(CalendarView, _super);

    function CalendarView() {
      return CalendarView.__super__.constructor.apply(this, arguments);
    }

    CalendarView.prototype.initialize = function() {
      return this.render.on('user-request-main', this.renderMain, this);
    };

    CalendarView.prototype.renderMain = function() {
      return this.render.blit(function() {
        var buffer;
        return buffer = new Plugin.global.Calendar({
          el: this.el
        });
      });
    };

    CalendarView.prototype.printCalendar = function() {
      var content, first_date, i, last_date, mominst, row, rows, _i;
      rows = [];
      mominst = moment().startOf('month');
      first_date = mominst.clone().startOf('month');
      last_date = mominst.clone().endOf('month');
      mominst.day(0);
      while (true) {
        row = {
          title: mominst.format('w'),
          cols: []
        };
        for (i = _i = 0; _i <= 6; i = ++_i) {
          row.cols.push({
            value: mominst.format('D'),
            attributes: {
              stamp: mominst.format('X'),
              month: mominst.month()
            }
          });
          mominst.add(1, 'day');
        }
        rows.push(row);
        if (mominst.isAfter(last_date)) {
          break;
        }
      }
      content = this.template({
        rows: rows,
        title: first_date.format('MMMM'),
        month: first_date.month()
      });
      return this.$el.html(content);
    };

    return CalendarView;

  })(Plugin.Blueprint.get('view'));

  Plugin["new"](Calendar).view(CalendarView);

}).call(this);
