// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    $.fn.combobox = function() {
      var options, text;
      options = this.find('.options').hide();
      text = this.find('.text');
      text.on('click', (function(_this) {
        return function() {
          options.show();
          options.width(text.outerWidth());
          options.css(text.offset());
          return $(document).on('click', function(ev) {
            if (!$.contains(_this[0], ev.target)) {
              return options.hide();
            }
          });
        };
      })(this));
      return options.find('.option').on('click', function() {
        text.val($(this).text());
        return options.hide();
      });
    };
    return $;
  });

}).call(this);
