// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $.fn.loading = function(enable) {
      var additional, element, key, offset, style, styleJSON, val;
      if (enable == null) {
        enable = true;
      }
      if (enable) {
        this.css('visibility', 'hidden');
        offset = this.offset();
        additional = {};
        if (offset.top === 0) {
          offset.top = window.innerHeight / 2;
        }
        if (offset.left === 0) {
          offset.left = window.innerWidth / 2;
          additional['margin-left'] = "-45px";
          additional['margin-top'] = "0";
        }
        styleJSON = {
          'position': 'absolute',
          'top': "" + offset.top + "px",
          'left': "" + offset.left + "px",
          'width': "" + (this.outerWidth()) + "px",
          'height': "" + (this.outerHeight()) + "px",
          'z-index': '100',
          'text-align': 'center',
          'display': 'table'
        };
        _.extend(styleJSON, additional);
        style = "";
        for (key in styleJSON) {
          val = styleJSON[key];
          style += "" + key + ": " + val + "; ";
        }
        element = $("\n<div style=\"" + style + "\" class='loading-overlay'>\n	<p style='display: table-cell'>\n		Loading...\n	</p>\n</div>\n");
        $(document.body).append(element);
        app.clearer.add('remove', 'html', element);
      } else {
        $('.loading-overlay').remove();
        this.css('visibility', 'visible');
      }
      return this;
    };
  })(jQuery);

}).call(this);
