// Generated by CoffeeScript 1.7.1
(function() {
  var New,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  New = (function(_super) {
    __extends(New, _super);

    function New() {
      return New.__super__.constructor.apply(this, arguments);
    }

    New.prototype.events = {
      'submit form': function(ev) {
        return ev.preventDefault();
      },
      'click .button.dateselect': 'dateselect'
    };

    New.prototype.render = function() {
      return this.$el.html(this.template());
    };

    New.prototype.dateselect = function(ev) {
      return console.log('will open dateselect');
    };

    return New;

  })(Backbone.View);

  app.get('plugin').get('task').get('imports').set('views/new.js', {
    local: true,
    "import": New
  });

}).call(this);
