// Generated by CoffeeScript 1.7.1
(function() {
  define({
    load: function(name, req, callback, config) {
      return req(["text!" + name + ".dotjs", 'dotjs'], function(content, dot) {
        return callback(dot.template(content));
      });
    }
  });

}).call(this);
