// Generated by CoffeeScript 1.7.1
(function() {
  var Plugin, Task, TaskRouter, TaskView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Plugin = app.get('plugin');

  Task = (function(_super) {
    __extends(Task, _super);

    function Task() {
      return Task.__super__.constructor.apply(this, arguments);
    }

    Task.prototype.defaults = {
      id: 'task',
      title: 'Tasks',
      navigatable: true,
      assets: {
        template: 'new.template.html',
        js: 'views/new.js'
      },
      submenus: [
        {
          link: 'list',
          title: 'Show a list of tasks'
        }, {
          link: 'new',
          title: 'Create a new'
        }
      ]
    };

    return Task;

  })(Plugin.Blueprint.get('model'));

  TaskView = (function(_super) {
    __extends(TaskView, _super);

    function TaskView() {
      return TaskView.__super__.constructor.apply(this, arguments);
    }

    TaskView.prototype.initialize = function() {
      return this.render.on('user-request-main', this.renderMain, this);
    };

    TaskView.prototype.renderMain = function() {
      return this.render.blit(function() {
        return this.$el.html('<h2>Task main</h2>');
      });
    };

    TaskView.prototype.renderList = function() {
      return this.render.blit(function() {
        return this.$el.html('<h2>Task list</h2>');
      });
    };

    TaskView.prototype.renderNew = function() {
      return this.render.blit(function() {
        var tn;
        tn = new Plugin.local.New({
          el: this.el
        });
        tn.template = Plugin.getAsset('template', 'new.template.html');
        return tn.render();
      });
    };

    return TaskView;

  })(Plugin.Blueprint.get('view'));

  TaskRouter = (function(_super) {
    __extends(TaskRouter, _super);

    function TaskRouter() {
      return TaskRouter.__super__.constructor.apply(this, arguments);
    }

    TaskRouter.prototype.routes = {
      'list': 'render-list',
      'new': 'render-new'
    };

    TaskRouter.prototype['render-list'] = function() {
      return Plugin.get('task').view.renderList();
    };

    TaskRouter.prototype['render-new'] = function() {
      return Plugin.get('task').view.renderNew();
    };

    return TaskRouter;

  })(Plugin.Blueprint.get('router'));

  Plugin["new"](Task).view(TaskView).router(TaskRouter);

}).call(this);
